# Generated by Django 5.2.6 on 2025-10-02 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('bread', 'Bread'), ('injera', 'Injera'), ('flour', 'Wheat Flour'), ('yeast', 'Yeast'), ('enhancer', 'Enhancer')], max_length=20)),
                ('product_name', models.CharField(max_length=100)),
                ('product_id', models.PositiveIntegerField(blank=True, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('transaction_type', models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocktransaction_new_set', to='branches.branch')),
            ],
        ),
    ]
