# Generated by Django 5.2.6 on 2025-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTransaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='product_type',
            field=models.CharField(choices=[('bread', 'Bread'), ('injera', 'Injera'), ('flour', 'Flour'), ('yeast', 'Yeast'), ('enhancer', 'Enhancer')], max_length=20),
        ),
    ]
