# Generated by Django 5.2.6 on 2025-10-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockTransaction', '0002_alter_stocktransaction_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
