# Generated by Django 5.2.6 on 2025-10-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_remove_revenue_branch_financerecord_delete_expense_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Finance Report',
                'verbose_name_plural': 'Finance Reports',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='FinanceRecord',
        ),
    ]
