# Generated by Django 5.2.6 on 2025-10-02 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financereport_delete_financerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinanceReport',
        ),
    ]
