# Generated by Django 5.2.6 on 2025-10-03 11:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('finance', '0004_delete_financereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=50)),
                ('product_name', models.CharField(blank=True, max_length=200)),
                ('quantity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('transaction_type', models.CharField(choices=[('revenue', 'Revenue'), ('expense', 'Expense')], max_length=10)),
                ('source_app', models.CharField(blank=True, max_length=100, null=True)),
                ('source_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product_type'], name='finance_tra_product_b45561_idx'), models.Index(fields=['transaction_type'], name='finance_tra_transac_2a23c2_idx'), models.Index(fields=['created_at'], name='finance_tra_created_ef4f06_idx')],
            },
        ),
    ]
