# Generated by Django 5.2.6 on 2025-10-04 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_userbranch_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbranch',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_users', to='branches.branch'),
        ),
    ]
