# Generated by Django 5.2.6 on 2025-09-29 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enhancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount_used_per_batch', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Injera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_code', models.CharField(max_length=50)),
                ('diameter', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fermented_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WheatFlour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=100)),
                ('package_size', models.FloatField()),
                ('stock_kg', models.FloatField()),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Yeast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('package_weight', models.FloatField()),
                ('stock_units', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='bread',
            old_name='created_at',
            new_name='baked_at',
        ),
        migrations.RemoveField(
            model_name='bread',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='bread',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='bread',
            name='weight',
            field=models.FloatField(default=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bread',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
