# Generated by Django 5.2.6 on 2025-09-29 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0003_branch_inventory_stocktransaction'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_id',
            new_name='object_id',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='content_type',
            field=models.ForeignKey(default=1, limit_choices_to={'model__in': ['bread', 'injera', 'wheatflour', 'yeast', 'enhancer']}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('branch', 'content_type', 'object_id')},
        ),
    ]
