# Generated by Django 5.2.6 on 2025-09-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0004_rename_product_id_inventory_object_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='object_id',
            new_name='product_id',
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='product_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='content_type',
        ),
    ]
