# Generated by Django 5.2.6 on 2025-09-30 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0005_rename_object_id_inventory_product_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktransaction',
            old_name='transaction_date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='note',
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bakery.branch'),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='product_type',
            field=models.CharField(choices=[('bread', 'Bread'), ('injera', 'Injera'), ('flour', 'Wheat Flour'), ('yeast', 'Yeast'), ('enhancer', 'Enhancer')], default=2, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out')], max_length=3),
        ),
    ]
