# Generated by Django 5.2.6 on 2025-09-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0006_rename_transaction_date_stocktransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bakery.branch'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='product_name',
            field=models.CharField(max_length=100),
        ),
    ]
