# Generated by Django 5.2.6 on 2025-09-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0007_alter_stocktransaction_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
