# Generated by Django 5.2.6 on 2025-09-30 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0008_stocktransaction_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='product_id',
        ),
    ]
