# Generated by Django 5.2.6 on 2025-09-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0009_remove_stocktransaction_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
