# Generated by Django 5.2.6 on 2025-10-02 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0010_stocktransaction_product_id'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
