# Generated by Django 5.2.6 on 2025-10-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0011_alter_stocktransaction_branch_alter_inventory_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
