# Generated by Django 5.2.6 on 2025-10-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0012_delete_stocktransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bread',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.RenameField(
            model_name='injera',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='bread',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enhancer',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enhancer',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injera',
            name='selling_price',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yeast',
            name='cost_per_unit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yeast',
            name='selling_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=8),
            preserve_default=False,
        ),
    ]
