# Generated by Django 5.2.6 on 2025-10-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0013_rename_price_bread_cost_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WheatFlour',
        ),
        migrations.RenameField(
            model_name='bread',
            old_name='cost_price',
            new_name='electricity_birr',
        ),
        migrations.RenameField(
            model_name='bread',
            old_name='weight',
            new_name='enhancer_kg',
        ),
        migrations.RenameField(
            model_name='enhancer',
            old_name='type',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='enhancer',
            old_name='cost_per_unit',
            new_name='cost_per_kg',
        ),
        migrations.RenameField(
            model_name='injera',
            old_name='cost_price',
            new_name='electricity_birr',
        ),
        migrations.RenameField(
            model_name='injera',
            old_name='diameter',
            new_name='flour_kg',
        ),
        migrations.RenameField(
            model_name='yeast',
            old_name='cost_per_unit',
            new_name='cost_per_kg',
        ),
        migrations.RemoveField(
            model_name='bread',
            name='baked_at',
        ),
        migrations.RemoveField(
            model_name='enhancer',
            name='amount_used_per_batch',
        ),
        migrations.RemoveField(
            model_name='enhancer',
            name='selling_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='injera',
            name='batch_code',
        ),
        migrations.RemoveField(
            model_name='injera',
            name='fermented_days',
        ),
        migrations.RemoveField(
            model_name='injera',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='package_weight',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='selling_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='yeast',
            name='stock_units',
        ),
        migrations.AddField(
            model_name='bread',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bread',
            name='flour_kg',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='water_birr',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bread',
            name='yeast_kg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enhancer',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injera',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='injera',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injera',
            name='water_birr',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='injera',
            name='yeast_kg',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yeast',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yeast',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enhancer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_type',
            field=models.CharField(choices=[('bread', 'Bread'), ('injera', 'Injera'), ('flour', 'Flour'), ('yeast', 'Yeast'), ('enhancer', 'Enhancer')], max_length=20),
        ),
    ]
